#!/usr/bin/python

import string, sys
import re
import subprocess
import logging
import datetime
import argparse
from ezistore.config import *
from ezistore.tools import *
from ezistore.client import *
from ezistore.gpg import *

def ezistorecli():
    default_config_file = '/opt/ezi-store/config-client'
    LOG = logging.getLogger("ezistore.ezistorecli")
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--config", help="specify config file, default: %s" % (default_config_file),
                         action="store", metavar="FILE", default=default_config_file)
    parser.add_argument("-a", "--add", help="add a password", action="store_true")
    parser.add_argument("-l", "--login", help="specify login", action="store", metavar='login')
    parser.add_argument("-p", "--password", help="specify password", action="store", metavar='pass')
    parser.add_argument("-c", "--comment", help="specify a comment", action="store", metavar='comment')
    parser.add_argument("-u", "--url", help="specify an url", action="store", metavar='url')
    parser.add_argument("-s", "--search", help="search with a pattern", action="store", metavar='PATTERN')
    parser.add_argument("-d", "--delete", help="delete entry in base", action="store", metavar='id')

    args = parser.parse_args()
    configfilename=args.config

    default_config = {'server': {
                                  'bind_address': '127.0.0.1',
                                  'bind_port': '40000'},
                      'logging': {
                                  'logfilename': '/var/log/ezistore'},
                      'gpg': {
                              'gnupghome': '/opt/ezi-store/gpg',
                              'key_type': 'RSA',
                              'key_length': '4096',
                              'expire_date': '365d',
                              'name_real': 'Ezi Store',
                              'name_email': 'ezi-store@zigzag.sx',
                              'name_comment': 'ezi-store server key'}
                     }
    config = Config(configfilename)
    if config == None:
        LOG.error("Can't load config file")
        return None
    merged_config = config.load(default_config)
    if merged_config == None:
        LOG.error("Can't merge config file")
        return None

    init_log(ROOT_LOG='ezistore', filename=merged_config['logging']['logfilename'])

    gpg = Gpg(merged_config)
    client = Client(merged_config)
    
    if args.add:
        if args.login == None:
            print "Missing argument: -l <login>"
            exit(1)
        if args.password == None:
            print "Missing argument: -p <password>"
            exit(1)
        if args.comment == None:
            print "Missing argument: -c \"comment\""
            exit(1)
        if args.url == None:
            args.url = 'N/A'
        message = gpg.encode(data='ADD %s|%s|%s|%s' % (args.login,args.password,args.comment,args.url), keyid=merged_config['gpg']['server_key'])
        print gpg.decode(data=client.do_query(message=message), keyid=merged_config['gpg']['client_key'])

    if args.search:
        message = gpg.encode(data='FIND ' + args.search, keyid=merged_config['gpg']['server_key'])
        print gpg.decode(data=client.do_query(message=message), keyid=merged_config['gpg']['client_key'])

    if args.delete:
        message = gpg.encode(data='DELETE ' + args.delete, keyid=merged_config['gpg']['server_key'])
        print gpg.decode(data=client.do_query(message=message), keyid=merged_config['gpg']['client_key'])

if __name__ == '__main__':
    ezistorecli()
